version: '3.8'
services:

#  db:
#    build: ./mysql
#    container_name: mysql_db
#    restart: always
#    volumes:
#      - ./sharevolume/mysql:/var/lib/mysql
#    ports:
#      - 3306:3306
#    environment:
#      - MYSQL_ROOT_PASSWORD=1234

  php:
    build: ./php
    container_name: php_server
    restart: always
    depends_on:
      - db
    volumes:
      - ./public_html:/var/www/html
    ports:
      - 80:80

#  pma:
#    image: phpmyadmin/phpmyadmin
#    container_name: phpmyadmin_app
#    restart: always
#    depends_on:
#      - db
#    ports:
#      - 8000:80
